# docker-compose.prod.yml
services:
  app1:
    image: ghcr.io/htwar/cs-396-project-2-app:${APP_TAG:-main}
    environment: { SERVER_NAME: app1 }
  app2:
    image: ghcr.io/htwar/cs-396-project-2-app:${APP_TAG:-main}
    environment: { SERVER_NAME: app2 }
  app3:
    image: ghcr.io/htwar/cs-396-project-2-app:${APP_TAG:-main}
    environment: { SERVER_NAME: app3 }

  ui:
    image: ghcr.io/htwar/cs-396-project-2-ui:${APP_TAG:-main}
    labels:
      - traefik.enable=true
      - traefik.http.routers.ui.rule=PathPrefix(`/`)
      - traefik.http.routers.ui.entrypoints=websecure
      - traefik.http.routers.ui.tls=true
