name: CI
on:
  pull_request:
  push:
    branches: [main]

jobs:
  backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: python -m pip install --upgrade pip
      - run: pip install -r requirements.txt black ruff mypy pytest
      - run: black --check .
      - run: ruff check .
      - run: mypy .
      # Don't fail the build if no tests are collected (pytest exit code 5)
      - name: pytest
        run: |
          set -e
          pytest -q || code=$?
          if [ "${code:-0}" -eq 5 ]; then
            echo "pytest: no tests collected; continuing."; exit 0
          elif [ "${code:-0}" -ne 0 ]; then
            exit ${code}
          fi

  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: file-repo-ui
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
